### ISSUE TITLE
Set up Continuous Integration

### ISSUE THREAD

**Issue by raaaahman** [WordPress/wp-feature-notifications#10]
Since we are hosting the plugin code on GitHub, and this is an open source project, [Travis CI](https://github.com/marketplace/travis-ci/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW43MA==#pricing-and-setup) seems to be the way to go.

The benefits of continuous integration will be to check on each PR:

- The passing or failing of our automated tests suite (see #12, #13 and #15 )
- The respect of coding standards (see #11 )
- The compatibility with different server environments (see #14 )

**Comment by szepeviktor** [comment]
What about **superior** [GitHub Actions](https://github.com/marketplace?type=actions&query=WordPress)?

**Comment by szepeviktor** [comment]
this is what I call "3 basic tests" - turns out they are for **elite** developers

1. Lint source code (syntax check) - see `php -h | grep Syntax` why it is called "lint"
1. Check coding style and adhere to EditorConfig
1. Do static analysis

[The newcomer](https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/Continuous-integration-Continuous-delivery.md) - Number Zero: :zero: _Check non-ASCII characters in the source code_

**Comment by jonathanbossenger** [comment]
I would love to see this project make use of GitHub actions, as a model for how an open source WordPress project can leverage their benefits.

**Comment by youknowriad** [comment]
Gutenberg is already 100% Github actions powered. you might want to use some of the jobs there.

**Comment by jonathanbossenger** [comment]
@raaaahman it might be worthwhile to review what Gutenberg already does, and see how much of that we can use.

**Comment by raaaahman** [comment]
The [WordPress Core team has worked on GitHub actions](https://make.wordpress.org/core/2020/10/15/introducing-github-actions-for-automated-testing/) as well, we'd probably can draw inspiration from there too.

**Comment by erikyo** [comment]
Has been already setup :) 

duplicated issue of #54, #59...
