### ISSUE TITLE
set Dependabot only for security updates

### ISSUE THREAD

**Issue by erikyo** [WordPress/wp-feature-notifications#149]
## What problem does this address?
What we are interested in is that there aren't any serious security problems, if we get so many pr for each updated package we risk losing sight of the real pr

## What is your proposed solution?
According [to this article](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates) just set `open-pull-requests-limit` to 0 [here](https://github.com/WordPress/wp-feature-notifications/blob/bac7a329597e2ddc8257d8c51c5f5f2fcc5b686a/.github/dependabot.yml#L9) for disabling version updates for npm dependencies

linked to #244

**Comment by Sephsekla** [comment]
Hmmm, I'm not sure about this. We do have a separate area for dependabot security alerts at https://github.com/WordPress/wp-feature-notifications/security/dependabot already, and I'd rather not lose the ability to keep packages up to date preemptively.

**Comment by erikyo** [comment]
Ok, so here we have to decide (maybe tomorrow in the weekly office hours) because due to the number of packages and the frequency with which we update them, getting a PR for each slightest change in version of a package could become cumbersome.  I agree for security updates, which could protect those who collaborate, but updating packages in our case is not a priority imho

**Comment by Sephsekla** [comment]
You raise a good point. What about changing the frequency of dependabot PRs to weekly or less frequent? Might cut down on noise a little bit.

**Comment by erikyo** [comment]
it is not so much about the number of alerts, it is just that if I update packages I want to be aware that I am doing so. And check for side effects. In the end, we don't have e2e tests to do this, so a package update could change the behaviour of the plugin

**Comment by Sephsekla** [comment]
Hmm, that's fair. Though I'd argue that we should be dictating that through npm/composer version ranges - assuming semantic versioning, minor updates should only be bugfixes and security updates.

**Comment by johnhooks** [comment]
@Sephsekla I would agree if we can depend on semantic versioning, but issues still come up because of version releases that don't follow the rules. 

What do you think about weekly scheduled bot PRs on Thursdays that are automated merged in a `dependencies` branch of `develop`. That would give us a week to manually try the change in a separate branch before the weekly meeting. We create a habit of discussing issues with `dependencies` branch in the meeting, and if there are none we always merge it in. This would reduce the number of bot PR sitting in the list on GitHub, and create a schedule and workflow to manage them as a team.

These are just thoughts, please feel free to critique.
