### ISSUE TITLE
Notification Hub overlays the admin menu bar

### ISSUE THREAD

**Issue by johnhooks** [WordPress/wp-feature-notifications#191]
### Description

When the Notification Hub is expanded, it overlays the admin menu bar and the icon to toggle the panel closed.

### Step-by-step reproduction instructions

1. Click the notification button in the top right corner.

### Screenshots, screen recording, code snippet

![31E00690-F6D4-4200-8C50-502A0D9B9AED](https://user-images.githubusercontent.com/20690965/228366612-3fa8842d-7528-42ae-8c31-ca1a40aad820.png)

### Environment info

- Latest `develop` branch 
- Safari on iOS
- Chromium on Max

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except WP Feature Notifications.

Yes

**Comment by johnhooks** [comment]
@erikyo pointed out the Hub overlays the menu-bar in the design. This feels out of sync with how the other icons in the menu-bar on mobile function. They all drop down.

**Comment by johnhooks** [comment]
The messages also feel tight. Would filling the entire screen on mobile be a better experience?

**Comment by erikyo** [comment]
@johnhooks in this case we need think about a "swipe to close " (like the gmail app drawer)

**Comment by johnhooks** [comment]
@folletto What do you think, does this function as intended? (Other than the missing notification bell icon, which should be in the top right corner to close the drawer)

**Comment by folletto** [comment]
I think that the issue here is that the current screenshot above is still missing the icon to toggle open/close. Without that it "feels" wrong. ;) 

My suggestion here is to:
1. Introduce the bell toggle button (with full accessibility aria and keyboard nav) as per designs so it's possible to close this.
2. On mobile go full screen also to the side, don't leave gaps that show the page underneath. On mobile we can treat this effectively as a "full screen" modal kind of behaviour to optimize space use and readability (nobody cares which page is under when they are reading the notifications).

<img width="320" alt="Screenshot 2023-03-29 at 11 49 39" src="https://user-images.githubusercontent.com/4389/228511109-2a078732-5302-47bc-a46b-4dc355cb6eb9.png">

Note that the bell icon size on mobile must match the underlying admin bar. As the admin bar grows on mobile, the icon should scale proportionally to match.

That said, I think it's also ok if we want to keep the top bar visible on mobile, as a sort of in-between. It changes a bit the behaviour as the sidebar currently covers the admin bar, but it's doable if there's a strong push for keeping the admin bar visible.

**Comment by johnhooks** [comment]
@folletto thank you, that helps a lot. We will do two versions, one with the admin menu bar on top and one total full screen. Then we can make a choice based on feedback.

**Comment by johnhooks** [comment]
It's been determined this is an intentional part of the design. And we have added a icon to close the drawer, which makes it less awkward.
